Awojtys\TicketServBundle\Entity\Config:
    type: entity
    table: null
    repositoryClass: Awojtys\TicketServBundle\Entity\ConfigRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '255'
        value:
            type: string
            nullable: true
            length: '255'
    lifecycleCallbacks: {  }
