Awojtys\TicketServBundle\Entity\Status:
    type: entity
    table: null
    repositoryClass: Awojtys\TicketServBundle\Entity\StatusRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
    oneToMany:
         tickets:
             targetEntity: Ticket
             mappedBy: status