Awojtys\TicketServBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Awojtys\TicketServBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nickname:
            type: string
            length: '255'
        password:
            type: string
            length: '128'
        email:
            type: string
            length: '255'
        role:
            type: string
            length: '30'
        avatar:
            type: string
            length: '255'
        switched:
            type: smallint
    lifecycleCallbacks: {  }
    oneToMany:
         tickets:
             targetEntity: Ticket
             mappedBy: user
         tickets2:
             targetEntity: Ticket
             mappedBy: user
